package org.protege;

import org.protege.editor.owl.OWLEditorKit;
import org.protege.ontograf.actions.ExportImageAction;
import org.protege.ontograf.actions.OpenGraphAction;
import org.protege.ontograf.actions.SaveGraphAction;
import org.protege.ontograf.common.GraphController;

/**
*
* @author Administrator
*/
public class NewJFrame extends javax.swing.JFrame {
	private GraphController graphController;
   /** Creates new form NewJFrame */
   public NewJFrame() {
       initComponents();       
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
	   graphController = new GraphController(this, new OWLEditorKit());
       jLabel1 = new javax.swing.JLabel();
       jToolBar1 = new javax.swing.JToolBar();
       openButton = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setText("jLabel1");

       jToolBar1.setRollover(true);

       openButton.setText("open");
       openButton.setFocusable(false);
       openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
       openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
       openButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               openButtonActionPerformed(evt);
           }
       });
       jToolBar1.add(openButton);
       jToolBar1.add(new OpenGraphAction(this, graphController));
       jToolBar1.add(new SaveGraphAction(this, graphController));
       jToolBar1.add(new ExportImageAction(this, graphController.getGraph().getCanvas()));

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(125, 125, 125)
                       .addComponent(jLabel1))
                   .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(186, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
               .addComponent(jLabel1)
               .addGap(120, 120, 120))
       );

       pack();
   }// </editor-fold>

   private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new NewJFrame().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JLabel jLabel1;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JButton openButton;
   // End of variables declaration

}
